### ISSUE TITLE
Provide fallback message or data when user denies geolocation

### ISSUE THREAD

**Issue by axeberg** [chas-academy/08-weather-app-hampusfredriksson#1]
If the user clicks "Block" when the browser asks for geolocation the application should at the very least provide a fallback message explaining that geolocation is required, if not that then show default weather for Stockholm or some other city!

@hampusfredriksson  make sure to mention me when you close this issue to indicate that this has been deployed and is ready for grading.

**Comment by hampusfredriksson** [comment]
latest commit closes this oki
